"""Compliance Reporting Engine for Executive, Technical, and Audit-Ready Exports."""

import json
from datetime import datetime, timezone
from typing import Any, Dict, List
from python_hunter.domain.compliance.models import ComplianceAssessmentModel, ComplianceGapModel


class ComplianceReportingEngine:
    """Generates structured compliance audit reports in JSON, CSV, and text/PDF formats."""

    def generate_audit_package(
        self,
        assessment: ComplianceAssessmentModel,
        gaps: List[ComplianceGapModel],
        organization_name: str = "Default Organization"
    ) -> Dict[str, Any]:
        """Generates an audit-ready compliance package with cryptographic report signature."""
        now = datetime.now(timezone.utc).isoformat()

        report_data = {
            "title": "Enterprise Compliance & Security Assurance Audit Package",
            "disclaimer": "This document is a technical compliance mapping and evidence assessment report generated by Python Hunter. It does not constitute a formal third-party regulatory certification.",
            "generation_timestamp": now,
            "organization": organization_name,
            "organization_id": assessment.organization_id,
            "framework_id": assessment.framework_id,
            "assessment_id": assessment.assessment_id,
            "assessment_period": assessment.assessment_period,
            "assessor": assessment.assessor,
            "reviewer": assessment.reviewer or "N/A",
            "status": assessment.status.value,
            "overall_compliance_score": f"{assessment.overall_score}%",
            "gaps_count": len(gaps),
            "gaps": [
                {
                    "gap_id": g.gap_id,
                    "control_id": g.control_id,
                    "severity": g.severity,
                    "remediation_plan": g.remediation_plan,
                    "owner": g.owner,
                    "sla_status": g.sla_status.value
                }
                for g in gaps
            ]
        }

        # Cryptographic signature over report content
        import hashlib
        raw = json.dumps(report_data, sort_keys=True)
        report_data["report_signature_sha256"] = hashlib.sha256(raw.encode('utf-8')).hexdigest()

        return report_data

    def export_json(self, report_package: Dict[str, Any]) -> str:
        return json.dumps(report_package, indent=2)

    def export_csv(self, gaps: List[ComplianceGapModel]) -> str:
        lines = ["gap_id,control_id,severity,owner,sla_status,remediation_plan"]
        for g in gaps:
            clean_plan = g.remediation_plan.replace('"', '""')
            lines.append(f'"{g.gap_id}","{g.control_id}","{g.severity}","{g.owner}","{g.sla_status.value}","{clean_plan}"')
        return "\n".join(lines)
