"""Project Manifest and Discovery Data Models."""

from dataclasses import dataclass, field
from typing import Any
from python_hunter.domain.discovery.enums import (
    DirectoryCategory,
    FileCategory,
    PackageLayout,
    ProjectType,
)


@dataclass(frozen=True)
class FileMetadata:
    """Discovered file metadata representation."""

    relative_path: str
    size_bytes: int
    category: FileCategory
    extension: str
    is_python: bool = False
    is_hidden: bool = False
    is_ignored: bool = False
    is_symlink: bool = False
    mime_type: str = "text/plain"


@dataclass(frozen=True)
class DirectoryMetadata:
    """Discovered directory metadata representation."""

    relative_path: str
    category: DirectoryCategory
    is_hidden: bool = False
    is_ignored: bool = False


@dataclass(frozen=True)
class ManifestStatistics:
    """Summary statistics for project discovery."""

    total_files: int = 0
    python_files: int = 0
    configuration_files: int = 0
    dependency_files: int = 0
    test_files: int = 0
    total_bytes: int = 0
    ignored_files: int = 0
    total_directories: int = 0


@dataclass
class ProjectManifest:
    """Structured Project Manifest generated by Project Discovery Engine."""

    root_path: str
    project_name: str
    project_type: ProjectType = ProjectType.UNKNOWN
    type_confidence: float = 0.0
    package_layout: PackageLayout = PackageLayout.UNKNOWN
    is_git_repository: bool = False
    has_docker: bool = False
    has_ci_cd: bool = False
    has_virtual_env: bool = False
    
    files: list[FileMetadata] = field(default_factory=list)
    directories: list[DirectoryMetadata] = field(default_factory=list)
    entry_points: list[str] = field(default_factory=list)
    frameworks: list[str] = field(default_factory=list)
    test_frameworks: list[str] = field(default_factory=list)
    dependency_files: list[str] = field(default_factory=list)
    configuration_files: list[str] = field(default_factory=list)
    ci_files: list[str] = field(default_factory=list)
    container_files: list[str] = field(default_factory=list)
    metadata_info: dict[str, Any] = field(default_factory=dict)
    statistics: ManifestStatistics = field(default_factory=ManifestStatistics)
